export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER ='SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';

export const SET_UPDATES = 'SET_UPDATES';
export const SET_UPDATE = 'SET_UPDATE';
export const LIKE_UPDATE = 'LIKE_UPDATE';
export const UNLIKE_UPDATE = 'UNLIKE_UPDATE';
export const DELETE_UPDATE = 'DELETE_UPDATE';
export const POST_UPDATE = 'POST_UPDATE';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';